#docker-compose-superset.yml

services:
  db:
    image: postgres:13
    container_name: superset_db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - superset_db_home:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superset"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    volumes:
      - minio_db:/data

  redis:
    image: redis:latest
    container_name: superset_redis
    restart: unless-stopped

  superset-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset_init
    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin || true &&
      superset init"
    environment:
      SUPERSET_SECRET_KEY: your_secret_key_here
      DATABASE_DIALECT: postgresql
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_DB: superset
      DATABASE_USER: superset
      DATABASE_PASSWORD: superset
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - superset_home:/app/superset_home

  superset:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset_app
    command: >
      bash -c "/app/docker/docker-bootstrap.sh app-gunicorn"
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: your_secret_key_here
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://superset:superset@db:5432/superset
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      superset-init:
        condition: service_completed_successfully
    volumes:
      - superset_home:/app/superset_home
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  superset_home:
  superset_db_home:
  minio_db:

#networks:
#  superset-network:
#    driver: bridge

networks:
  default:
    external:
      name: om_shared_network